
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bodega_rails_development
  user: postgres
  password: 123
  host: localhost

test:
  <<: *default
  database: bodega_rails_test
  user: postgres
  password: 123
  host: localhost

production:
  <<: *default
  database: bodega_rails_production
  username: bodega_rails
  password: <%= ENV["BODEGA_RAILS_DATABASE_PASSWORD"] %>
